name: Build and Delpoy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Pull submodules
      run: git submodule update --init --recursive
      
    - name: Build
      run: make html
      
  deploy:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
    - name: Deploy
      run: ./deploy.sh
